FROM php:8.3-fpm

# Install Python, pip, venv and required dependencies
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    default-mysql-client \
    libzip-dev \
    zip \
    unzip \
 && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
#RUN docker-php-ext-install pdo_mysql zip

# Create virtualenv in /opt/venv
RUN python3 -m venv /opt/venv

# Install Python libraries in the virtualenv
RUN /opt/venv/bin/pip install --no-cache-dir astropy pillow mysql-connector-python watchdog

# Make virtualenv's python and pip the default
ENV PATH="/opt/venv/bin:$PATH"

# Copy and set permissions for the entrypoint script
COPY docker-entrypoint-qnap.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint-qnap.sh

# Set the new entrypoint
ENTRYPOINT ["/usr/local/bin/docker-entrypoint-qnap.sh"]