CREATE TABLE IF NOT EXISTS files (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    path VARCHAR(1024) NOT NULL,
    object VARCHAR(255),
    date_obs DATETIME,
    exptime FLOAT,
    filter VARCHAR(50),
    imgtype VARCHAR(50),
    -- Extended metadata
    xbinning INT,
    ybinning INT,
    gain FLOAT,
    `offset` FLOAT,
    xpixsz FLOAT,
    ypixsz FLOAT,
    instrume VARCHAR(255),
    set_temp FLOAT,
    ccd_temp FLOAT,
    telescop VARCHAR(255),
    focallen FLOAT,
    focratio FLOAT,
    ra FLOAT,
    `dec` FLOAT,
    centalt FLOAT,
    centaz FLOAT,
    airmass FLOAT,
    pierside VARCHAR(50),
    siteelev FLOAT,
    sitelat FLOAT,
    sitelong FLOAT,
    focpos INT,
    -- Housekeeping
    thumb MEDIUMBLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    -- Indexes
    UNIQUE INDEX idx_path (path),
    INDEX idx_object (object),
    INDEX idx_filter (filter),
    INDEX idx_imgtype (imgtype),
    INDEX idx_instrume (instrume),
    INDEX idx_telescop (telescop)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;